const bankList = [
  {
    code: "044",
    name: "Access Bank",
    country: "NG",
    nameEnquiryRequired: true,

    flag: require("@/assets/img/bank-logos/access-bank.png"),
  },
  {
    code: "076",
    name: "Polaris Bank",
    country: "NG",
    nameEnquiryRequired: true,

    flag: require("@/assets/img/bank-logos/polaris-bank.png"),
  },
  {
    code: "101",
    name: "Providus Bank",
    country: "NG",
    nameEnquiryRequired: true,

    flag: require("@/assets/img/bank-logos/Providus_Bank_logo.png"),
  },
  {
    code: "125",
    name: "Rubies MFB",
    country: "NG",
    nameEnquiryRequired: true,

    flag: require("@/assets/img/bank-logos/rubies.png"),
  },
  {
    code: "51310",
    name: "Sparkle Microfinance Bank",
    country: "NG",
    nameEnquiryRequired: true,

    flag: require("@/assets/img/bank-logos/sparkle-microfinance-bank.png"),
  },
  {
    code: "221",
    name: "Stanbic IBTC Bank",
    country: "NG",
    nameEnquiryRequired: true,

    flag: require("@/assets/img/bank-logos/stanbic-ibtc-bank.png"),
  },
  {
    code: "068",
    name: "Standard Chartered Bank",
    country: "NG",
    nameEnquiryRequired: true,

    flag: require("@/assets/img/bank-logos/standard-chartered-bank.png"),
  },
  {
    code: "232",
    name: "Sterling Bank",
    country: "NG",
    nameEnquiryRequired: true,
    flag: require("@/assets/img/bank-logos/sterling-bank.png"),
  },
  {
    code: "100",
    name: "Suntrust Bank",
    country: "NG",
    nameEnquiryRequired: true,
    flag: require("@/assets/img/bank-logos/suntrust-bank.png"),
  },
  {
    code: "302",
    name: "TAJ Bank",
    country: "NG",
    nameEnquiryRequired: true,
    flag: require("@/assets/img/bank-logos/taj-bank.png"),
  },
  {
    code: "51211",
    name: "TCF MFB",
    country: "NG",
    nameEnquiryRequired: true,
    flag: require("@/assets/img/bank-logos/tcf-MFB.png"),
  },
  {
    code: "102",
    name: "Titan Bank",
    country: "NG",
    nameEnquiryRequired: true,
    flag: require("@/assets/img/bank-logos/Titan.png"),
  },
  {
    code: "032",
    name: "Union Bank of Nigeria",
    country: "NG",
    nameEnquiryRequired: true,
    flag: require("@/assets/img/bank-logos/union-bank-of-nigeria.png"),
  },
  {
    code: "033",
    name: "United Bank For Africa",
    country: "NG",
    nameEnquiryRequired: true,
    flag: require("@/assets/img/bank-logos/united-bank-for-africa.png"),
  },
  {
    code: "215",
    name: "Unity Bank",
    country: "NG",
    nameEnquiryRequired: true,
    flag: require("@/assets/img/bank-logos/unity-bank.png"),
  },
  {
    code: "566",
    name: "VFD",
    country: "NG",
    nameEnquiryRequired: true,
    flag: require("@/assets/img/bank-logos/v-banking.png"),
  },
  {
    code: "526",
    name: "Parallex Bank",
    country: "NG",
    nameEnquiryRequired: true,
    flag: require("@/assets/img/bank-logos/parallex.png"),
  },
  {
    code: "565",
    name: "One Finance",
    country: "NG",
    nameEnquiryRequired: true,
    flag: require("@/assets/img/bank-logos/one-finance.png"),
  },
  {
    code: "50211",
    name: "Kuda Bank",
    country: "NG",
    nameEnquiryRequired: true,
    flag: require("@/assets/img/bank-logos/Kuda.png"),
  },
  {
    code: "082",
    name: "Keystone Bank",
    country: "NG",
    nameEnquiryRequired: true,
    flag: require("@/assets/img/bank-logos/keystone-bank.png"),
  },

  {
    code: "035A",
    name: "ALAT by WEMA",
    country: "NG",
    nameEnquiryRequired: true,
    flag: require("@/assets/img/bank-logos/ALAT by WEMA.png"),
  },
  {
    code: "401",
    name: "ASO Savings and Loans",
    country: "NG",
    nameEnquiryRequired: true,
    flag: require("@/assets/img/bank-logos/aso-savings.png"),
  },
  {
    code: "50931",
    name: "Bowen Microfinance Bank",
    country: "NG",
    nameEnquiryRequired: true,
    flag: require("@/assets/img/bank-logos/Bowen-Microfinance.png"),
  },
  {
    code: "50823",
    name: "CEMCS Microfinance Bank",
    country: "NG",
    nameEnquiryRequired: true,
    flag: require("@/assets/img/bank-logos/CEMCS-Microfinance.png"),
  },
  {
    code: "023",
    name: "Citibank Nigeria",
    country: "NG",
    nameEnquiryRequired: true,
    flag: require("@/assets/img/bank-logos/Citibank.png"),
  },
  {
    code: "050",
    name: "Ecobank Nigeria",
    country: "NG",
    nameEnquiryRequired: true,
    flag: require("@/assets/img/bank-logos/ecobank-nigeria.png"),
  },
  {
    code: "035",
    name: "Wema Bank",
    country: "NG",
    nameEnquiryRequired: true,
    flag: require("@/assets/img/bank-logos/wema-bank.png"),
  },
  {
    code: "562",
    name: "Ekondo Microfinance Bank",
    country: "NG",
    nameEnquiryRequired: true,
    flag: require("@/assets/img/bank-logos/ekondo-microfinance-bank.png"),
  },
  {
    code: "011",
    name: "First Bank of Nigeria",
    country: "NG",
    nameEnquiryRequired: true,
    flag: require("@/assets/img/bank-logos/first-bank-of-nigeria.png"),
  },
  {
    code: "214",
    name: "First City Monument Bank",
    country: "NG",
    nameEnquiryRequired: true,
    flag: require("@/assets/img/bank-logos/first-city-monument-bank.png"),
  },
  {
    code: "00103",
    name: "Globus Bank",
    country: "NG",
    nameEnquiryRequired: true,
    flag: require("@/assets/img/bank-logos/globus-bank.png"),
  },
  {
    code: "058",
    name: "Guaranty Trust Bank",
    country: "NG",
    nameEnquiryRequired: true,
    flag: require("@/assets/img/bank-logos/guaranty-trust-bank.png"),
  },
  {
    code: "50383",
    name: "Hasal Microfinance Bank",
    country: "NG",
    nameEnquiryRequired: true,
    flag: require("@/assets/img/bank-logos/Hasal-Microfinance.png"),
  },
  {
    code: "030",
    name: "Heritage Bank",
    country: "NG",
    nameEnquiryRequired: true,
    flag: require("@/assets/img/bank-logos/heritage-bank.png"),
  },
  {
    code: "301",
    name: "Jaiz Bank",
    country: "NG",
    nameEnquiryRequired: true,
    flag: require("@/assets/img/bank-logos/Jaiz.png"),
  },

  {
    code: "070",
    name: "Fidelity Bank",
    country: "NG",
    nameEnquiryRequired: true,
    flag: require("@/assets/img/bank-logos/fidelity-bank.png"),
  },
  {
    code: "057",
    name: "Zenith Bank",
    country: "NG",
    nameEnquiryRequired: true,
    flag: require("@/assets/img/bank-logos/zenith-bank.png"),
  },
];

export default {
  getBankList() {
    return bankList;
  },
};
